return require('packer').startup(function(use)
	use 'wbthomason/packer.nvim'
	use 'neovim/nvim-lspconfig'
	use 'hrsh7th/nvim-cmp'
	use 'hrsh7th/cmp-nvim-lsp'
	use 'nvim-treesitter/nvim-treesitter'
	use 'nvim-tree/nvim-tree.lua'
	use 'nvim-tree/nvim-web-devicons'
	use 'nvim-lua/plenary.nvim'
	use 'nvim-telescope/telescope.nvim'
	use 'nvim-lualine/lualine.nvim'
	use 'kosayoda/nvim-lightbulb'
	use 'antoinemadec/FixCursorHold.nvim'
	use 'williamboman/mason.nvim'
	use 'onsails/lspkind.nvim'
	use 'windwp/nvim-autopairs'
	use 'ray-x/lsp_signature.nvim'
	use 'RishabhRD/popfix'
	use 'RishabhRD/nvim-lsputils'
    use {'TimUntersberger/neogit', requires = 'nvim-lua/plenary.nvim'}
    use 'akinsho/toggleterm.nvim'
    use 'f-person/git-blame.nvim'

	-- Themes
	use 'rafamadriz/neon'
    use 'indika-dev/eclipse.nvim'
    use 'folke/tokyonight.nvim'
    use 'sainnhe/gruvbox-material'
    use 'shaunsingh/nord.nvim'
    use 'sainnhe/edge'
    use 'Mofiqul/vscode.nvim'
    use 'doums/darcula'
    use 'mhartington/oceanic-next'
    use 'rose-pine/neovim'
    use 'joshdick/onedark.vim'
    use 'tanvirtin/monokai.nvim'
    use 'projekt0n/github-nvim-theme'
    use 'Shatur/neovim-ayu'
    use 'catppuccin/nvim'

end)
